/* 
© 2025 Aravinth Raj R. All rights reserved.
Unauthorized copying of this file, via any medium, is strictly prohibited.
Proprietary and confidential.  
Written by Aravinth Raj R <aravinthr235@gmail.com>, 2025.
*/
export const PRODUCTS_CONFIG = {
  addCategoryTitle: "Add Category",
  addItemTitle: "Add Item",
  editItemTitle: "Edit Item",
  addStockTitle: "Add Stock",
  category: "Category",
  quantity: "Quantity",
  mrp: "MRP",
  image: "Image",
  title: "Title",
  addButton: "Add",
  submitButton: "Submit",
  categoryToastSuccess: "Category Added Successfully",
  addItemToastSuccess: "Item Added Successfully",
  cartItemToastSuccess: "Item Added to Cart",
  all: "All",
  prQuantity: "Quantity : ",
  prMrp: "MRP : ₹ ",
  buyingPrice: "Buying Price",
  sellingPrice: "Selling Price",
  buyingPriceLabel: "Price : ",
  sellingPriceLabel: "Selling Price : ",
  editButton: "Edit",
  addToCartButton: "Add To Cart",
  sortedOptions: ["Sort By Title Asc", "Sort By Title Desc"],
  addItem: "Item Added to Cart",
  requiredData: "Please Fill the required data",
  nonZeroTerms: "Quantity and both prices should be non-zero",
  validImageTypes: [
    "image/jpeg",
    "image/png",
    "image/jpg",
    "image/webp",
    "image/gif",
  ],
  threshold: 10,
  acceptedImageTypes: " Accepted : jpeg, png, jpg, webp, gif",
  cancelIcon: "×",
  itemAlreadyInCart: "This item is already in your cart.",
  cartErrorMessage: "Something went wrong while adding the item.",
  outOfStock: "Item Out Of Stock",
  addStockButton: "Add",
  addedToCart: "Added To Cart",
  studentFavorite: "Student Favorite",
  budgetPick: "Budget Pick",
  fastMoving: "Fast Moving",
  lowStock: "No Stock",
  inStock: "In Stock",
  exploreSubtitle:
    "Campus-friendly essentials curated for quick and easy shopping.",
  deleteButton: "Delete",
  addStockPageTitle: "Add Stock",
  addStockPageButton: "Add Stock",
  addStockSearchSubtitle:
    "Find a product by title or category, then add fresh stock with the latest buying price.",
  currentStock: "Current Stock",
  updatedPrice: "Updated Price",
  stockAddedSuccess: "Stock added successfully.",
  deleteProductTitle: "Delete Product",
  deleteProductSubtitle:
    "This product will be hidden from customers and product listings.",
  confirmDeleteButton: "Yes, Delete",
  cancelDeleteButton: "Cancel",
};
